{"metadata":{"kernelspec":{"language":"python","display_name":"Python 3","name":"python3"},"language_info":{"name":"python","version":"3.10.12","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"},"kaggle":{"accelerator":"none","dataSources":[{"sourceId":3756201,"sourceType":"datasetVersion","datasetId":551982},{"sourceId":11090147,"sourceType":"datasetVersion","datasetId":6912860}],"dockerImageVersionId":30918,"isInternetEnabled":true,"language":"python","sourceType":"notebook","isGpuEnabled":false}},"nbformat_minor":4,"nbformat":4,"cells":[{"cell_type":"code","source":"# Path to the CORD-19 dataset (adjust as needed based on the dataset structure)\nsource_folder = '/kaggle/input/CORD-19-research-challenge/document_parses/pdf_json'\n\n# This uploads your service account JSON to the notebook\n# You'll need to add this file as a dataset in Kaggle\n# See instructions below on how to do this\nos.environ['GOOGLE_APPLICATION_CREDENTIALS'] = '../input/google-cloud/adc.json'\nbucket_name = \"sci_papers_bootcamp\"\nproject_name=\"jakub-le-wagon-bootcamp\"\nprefix = \"cord19/\"","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2025-03-19T16:13:34.692368Z","iopub.execute_input":"2025-03-19T16:13:34.692712Z","iopub.status.idle":"2025-03-19T16:13:34.697329Z","shell.execute_reply.started":"2025-03-19T16:13:34.692685Z","shell.execute_reply":"2025-03-19T16:13:34.696106Z"}},"outputs":[],"execution_count":28},{"cell_type":"code","source":"# Install gsutil in the Kaggle notebook\n!pip install gsutil\n!pip install google-cloud-storage","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2025-03-19T16:08:42.587941Z","iopub.execute_input":"2025-03-19T16:08:42.588356Z","iopub.status.idle":"2025-03-19T16:09:07.390353Z","shell.execute_reply.started":"2025-03-19T16:08:42.588320Z","shell.execute_reply":"2025-03-19T16:09:07.389309Z"},"collapsed":true,"jupyter":{"outputs_hidden":true}},"outputs":[{"name":"stdout","text":"Requirement already satisfied: gsutil in /usr/local/lib/python3.10/dist-packages (5.33)\nRequirement already satisfied: argcomplete>=3.5.1 in /usr/local/lib/python3.10/dist-packages (from gsutil) (3.6.0)\nRequirement already satisfied: crcmod>=1.7 in /usr/local/lib/python3.10/dist-packages (from gsutil) (1.7)\nRequirement already satisfied: fasteners>=0.14.1 in /usr/local/lib/python3.10/dist-packages (from gsutil) (0.19)\nRequirement already satisfied: gcs-oauth2-boto-plugin>=3.2 in /usr/local/lib/python3.10/dist-packages (from gsutil) (3.2)\nRequirement already satisfied: google-apitools>=0.5.32 in /usr/local/lib/python3.10/dist-packages (from gsutil) (0.5.32)\nRequirement already satisfied: httplib2==0.20.4 in /usr/local/lib/python3.10/dist-packages (from gsutil) (0.20.4)\nRequirement already satisfied: google-reauth>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from gsutil) (0.1.1)\nRequirement already satisfied: monotonic>=1.4 in /usr/local/lib/python3.10/dist-packages (from gsutil) (1.6)\nRequirement already satisfied: pyOpenSSL<=24.2.1,>=0.13 in /usr/local/lib/python3.10/dist-packages (from gsutil) (24.2.1)\nRequirement already satisfied: retry-decorator>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from gsutil) (1.1.1)\nRequirement already satisfied: six>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from gsutil) (1.17.0)\nRequirement already satisfied: google-auth==2.17.0 in /usr/local/lib/python3.10/dist-packages (from google-auth[aiohttp]==2.17.0->gsutil) (2.17.0)\nRequirement already satisfied: google-auth-httplib2>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from gsutil) (0.2.0)\nRequirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth==2.17.0->google-auth[aiohttp]==2.17.0->gsutil) (5.5.0)\nRequirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth==2.17.0->google-auth[aiohttp]==2.17.0->gsutil) (0.4.1)\nRequirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth==2.17.0->google-auth[aiohttp]==2.17.0->gsutil) (4.7.2)\nRequirement already satisfied: requests<3.0.0dev,>=2.20.0 in /usr/local/lib/python3.10/dist-packages (from google-auth[aiohttp]==2.17.0->gsutil) (2.32.3)\nRequirement already satisfied: aiohttp<4.0.0dev,>=3.6.2 in /usr/local/lib/python3.10/dist-packages (from google-auth[aiohttp]==2.17.0->gsutil) (3.11.12)\nRequirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /usr/local/lib/python3.10/dist-packages (from httplib2==0.20.4->gsutil) (3.2.0)\nRequirement already satisfied: boto>=2.29.1 in /usr/local/lib/python3.10/dist-packages (from gcs-oauth2-boto-plugin>=3.2->gsutil) (2.49.0)\nRequirement already satisfied: oauth2client>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from gcs-oauth2-boto-plugin>=3.2->gsutil) (4.1.3)\nRequirement already satisfied: pyasn1>=0.1.3 in /usr/local/lib/python3.10/dist-packages (from rsa<5,>=3.1.4->google-auth==2.17.0->google-auth[aiohttp]==2.17.0->gsutil) (0.6.1)\nRequirement already satisfied: pyu2f in /usr/local/lib/python3.10/dist-packages (from google-reauth>=0.1.0->gsutil) (0.1.5)\nRequirement already satisfied: cryptography<44,>=41.0.5 in /usr/local/lib/python3.10/dist-packages (from pyOpenSSL<=24.2.1,>=0.13->gsutil) (43.0.3)\nRequirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0dev,>=3.6.2->google-auth[aiohttp]==2.17.0->gsutil) (2.4.6)\nRequirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0dev,>=3.6.2->google-auth[aiohttp]==2.17.0->gsutil) (1.3.2)\nRequirement already satisfied: async-timeout<6.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0dev,>=3.6.2->google-auth[aiohttp]==2.17.0->gsutil) (5.0.1)\nRequirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0dev,>=3.6.2->google-auth[aiohttp]==2.17.0->gsutil) (25.1.0)\nRequirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0dev,>=3.6.2->google-auth[aiohttp]==2.17.0->gsutil) (1.5.0)\nRequirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0dev,>=3.6.2->google-auth[aiohttp]==2.17.0->gsutil) (6.1.0)\nRequirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0dev,>=3.6.2->google-auth[aiohttp]==2.17.0->gsutil) (0.2.1)\nRequirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0dev,>=3.6.2->google-auth[aiohttp]==2.17.0->gsutil) (1.18.3)\nRequirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.10/dist-packages (from cryptography<44,>=41.0.5->pyOpenSSL<=24.2.1,>=0.13->gsutil) (1.17.1)\nRequirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0dev,>=2.20.0->google-auth[aiohttp]==2.17.0->gsutil) (3.4.1)\nRequirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0dev,>=2.20.0->google-auth[aiohttp]==2.17.0->gsutil) (3.10)\nRequirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0dev,>=2.20.0->google-auth[aiohttp]==2.17.0->gsutil) (2.3.0)\nRequirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0dev,>=2.20.0->google-auth[aiohttp]==2.17.0->gsutil) (2025.1.31)\nRequirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.12->cryptography<44,>=41.0.5->pyOpenSSL<=24.2.1,>=0.13->gsutil) (2.22)\nRequirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.10/dist-packages (from multidict<7.0,>=4.5->aiohttp<4.0.0dev,>=3.6.2->google-auth[aiohttp]==2.17.0->gsutil) (4.12.2)\nRequirement already satisfied: google-cloud-storage in /usr/local/lib/python3.10/dist-packages (2.14.0)\nCollecting google-auth<3.0dev,>=2.23.3 (from google-cloud-storage)\n  Downloading google_auth-2.38.0-py2.py3-none-any.whl.metadata (4.8 kB)\nRequirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in /usr/local/lib/python3.10/dist-packages (from google-cloud-storage) (1.34.1)\nRequirement already satisfied: google-cloud-core<3.0dev,>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-storage) (2.4.1)\nRequirement already satisfied: google-resumable-media>=2.6.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-storage) (2.7.2)\nRequirement already satisfied: requests<3.0.0dev,>=2.18.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-storage) (2.32.3)\nRequirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-storage) (1.6.0)\nRequirement already satisfied: googleapis-common-protos<2.0dev,>=1.56.2 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage) (1.66.0)\nRequirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<4.0.0dev,>=3.19.5 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage) (3.20.3)\nRequirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3.0dev,>=2.23.3->google-cloud-storage) (5.5.0)\nRequirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3.0dev,>=2.23.3->google-cloud-storage) (0.4.1)\nRequirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3.0dev,>=2.23.3->google-cloud-storage) (4.7.2)\nRequirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage) (3.4.1)\nRequirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage) (3.10)\nRequirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage) (2.3.0)\nRequirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage) (2025.1.31)\nRequirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0dev,>=2.23.3->google-cloud-storage) (0.6.1)\nDownloading google_auth-2.38.0-py2.py3-none-any.whl (210 kB)\n\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m210.8/210.8 kB\u001b[0m \u001b[31m4.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n\u001b[?25hInstalling collected packages: google-auth\n  Attempting uninstall: google-auth\n    Found existing installation: google-auth 2.17.0\n    Uninstalling google-auth-2.17.0:\n      Successfully uninstalled google-auth-2.17.0\n\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\ngcs-oauth2-boto-plugin 3.2 requires google-auth==2.17.0, but you have google-auth 2.38.0 which is incompatible.\ngcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.12.0 which is incompatible.\ngoogle-cloud-bigtable 2.27.0 requires google-api-core[grpc]<3.0.0dev,>=2.16.0, but you have google-api-core 1.34.1 which is incompatible.\ngoogle-colab 1.0.0 requires google-auth==2.27.0, but you have google-auth 2.38.0 which is incompatible.\ngoogle-colab 1.0.0 requires notebook==6.5.5, but you have notebook 6.5.4 which is incompatible.\ngoogle-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.2.3 which is incompatible.\ngsutil 5.33 requires google-auth[aiohttp]==2.17.0, but you have google-auth 2.38.0 which is incompatible.\npandas-gbq 0.25.0 requires google-api-core<3.0.0dev,>=2.10.2, but you have google-api-core 1.34.1 which is incompatible.\u001b[0m\u001b[31m\n\u001b[0mSuccessfully installed google-auth-2.38.0\n","output_type":"stream"}],"execution_count":20},{"cell_type":"code","source":"from google.cloud.storage import transfer_manager\n\n# Get list of local files\nfiles = glob.glob(f\"{source_folder}/*.json\", recursive=True)\ntotal_files = len(files)\n\nprint(f\"Found {total_files} total local files\")\n","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2025-03-19T16:09:10.226110Z","iopub.execute_input":"2025-03-19T16:09:10.226534Z","iopub.status.idle":"2025-03-19T16:09:14.687122Z","shell.execute_reply.started":"2025-03-19T16:09:10.226500Z","shell.execute_reply":"2025-03-19T16:09:14.686105Z"}},"outputs":[{"name":"stdout","text":"Found 401214 total local files\n","output_type":"stream"}],"execution_count":21},{"cell_type":"code","source":"from pathlib import Path\n\ndef upload_files_to_gcs(source_directory, project, bucket, prefix):\n    \"\"\"\n    Uses Transfer manager to upload files in parallel to a GCS bucket.\n    Args:\n     source_directory (str): The local path of the source directory to upload files from.\n    \n    Returns:\n    \"\"\"\n    try:   \n        client = storage.Client(project=project)\n        bucket = client.bucket(bucket)\n        if not source_directory:\n            print(\"No local directory provided\")\n            return\n\n        # Get list of files already in the bucket\n        print(\"Listing existing files in the bucket...\")\n        existing_files = set()\n        blobs = bucket.list_blobs(prefix=prefix)\n        for blob in blobs:\n            # Remove the prefix to get just the relative path\n            if blob.name.startswith(prefix):\n                existing_files.add(blob.name[len(prefix):])\n        print(f\"Found {len(existing_files)} files already in the bucket\")\n        \n        \"\"\"\n        directory_as_path_obj = Path(source_directory)\n        paths = directory_as_path_obj.glob('*')\n        # Get the list of file paths, relative to the source directory and store them as strings\n        file_paths = [path for path in paths if path.is_file()]\n        relative_paths = [path.relative_to(source_directory) for path in file_paths]\n        string_paths = [str(path) for path in relative_paths]\n        \"\"\"\n        # Get list of local files\n        files = glob.glob(f\"{source_folder}/*.json\", recursive=True)\n        total_files = len(files)\n        \n        print(f\"Found {total_files} total local files\")\n        print(f\"Example: {files[0]}\")\n\n        to_upload = []\n        # Create manifest only for files that don't exist in the bucket\n        skipped = 0\n        for file_path in files:\n            relative_path = os.path.relpath(file_path, source_folder)\n            if relative_path not in existing_files:\n                to_upload.append(relative_path)\n            else:\n                skipped += 1\n    \n        print(f\"Initiating upload of {len(to_upload)} local files\")\n        print(f\"Starting with: {to_upload[0]}\")\n        results = transfer_manager.upload_many_from_filenames(\n            bucket = bucket,\n            filenames = to_upload,\n            source_directory = source_directory,\n            blob_name_prefix = prefix,\n            max_workers = 32,\n            skip_if_exists = True,\n        )\n    except Exception as e:\n        print(f\"Failed to upload files to GCS due to exception: {e}\")","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2025-03-19T16:40:56.147698Z","iopub.execute_input":"2025-03-19T16:40:56.148049Z","iopub.status.idle":"2025-03-19T16:40:56.156100Z","shell.execute_reply.started":"2025-03-19T16:40:56.148009Z","shell.execute_reply":"2025-03-19T16:40:56.154869Z"}},"outputs":[],"execution_count":40},{"cell_type":"code","source":"upload_files_to_gcs(source_folder, project_name, bucket_name, prefix)","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2025-03-19T16:41:00.000746Z","iopub.execute_input":"2025-03-19T16:41:00.001060Z","iopub.status.idle":"2025-03-19T17:46:36.814595Z","shell.execute_reply.started":"2025-03-19T16:41:00.001034Z","shell.execute_reply":"2025-03-19T17:46:36.809830Z"}},"outputs":[{"name":"stdout","text":"Listing existing files in the bucket...\nFound 2547 files already in the bucket\nFound 401214 total local files\nExample: /kaggle/input/CORD-19-research-challenge/document_parses/pdf_json/8f97e16f3842e4bbd2d5d1c0c95ac1e31993ec68.json\nInitiating upload of 398667 local files\nStarting with: d1b3822f36c739fbd34f63ddc02f845e85e921b2.json\n","output_type":"stream"}],"execution_count":41}]}